# Generated by Django 4.2.1 on 2023-05-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile_remove_book_favourite_remove_comment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
